version: '3'

services:
  server:
    build: .
    command: "go run main.go"
    environment:
      - DB_NAME=sample
      - DB_HOST=db
      - DB_USER=edgedb
      - DB_PASSWORD=development
      - DB_PORT=5656
      - USER_KEY=userprivatekey
      - SMTP_PORT=587
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PASSWORD=wybbslpzbhuinkrb
      - SMTP_USERNAME=sethukumarj.76@gmail.com
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: edgedb/edgedb
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
      - EDGEDB_SERVER_DATABASE=sample
      - EDGEDB_SERVER_PASSWORD=development
    volumes:
      - ./schema:/dbschema
      - ./credentials:/root/.config/edgedb/credentials
      - edgedb_data:/var/lib/edgedb/data
    ports:
      - "5656:5656"

volumes:
  edgedb_data: